Add container metadata to process payload
DataDog/gopsutil pull request #1
Opened 2016-12-29 23:32 UTC by z0br0wn

currently supports only docker

2016-12-30 15:39 UTC, conorbranagan requested changes

2016-12-30 15:39 UTC, conorbranagan commented on process/process_linux.go
> +		containers = make(map[string]ContainerStat)
It seems right to not fail everything if this call falls but we should at least log the error

2016-12-30 15:39 UTC, conorbranagan commented on docker/docker_linux.go
> +func CgroupPID(containerID string, base string) ([]string, error) {
maybe return `[]int32` instead since this is pids? also should we call it CgroupPIDs (plural) for clarity of what you're getting back?

2016-12-30 15:39 UTC, conorbranagan commented on docker/docker_linux.go
> +func CgroupPIDDocker(containerID string) (map[string]string, error) {
how does this return a map if the inner function returns an array?

2016-12-30 15:39 UTC, conorbranagan commented on process/process_linux.go
> +			container, _ := containers[pid]
does this work since it's a map[string] but pid is int32?

2016-12-30 15:39 UTC, conorbranagan commented on docker/docker.go
> +	Metadata map[string]string `json:"metadata"`
I think we would benefit from a more explicit structure here just including things we know we'll care about, such as Name, Image, ID, ..

2016-12-30 15:39 UTC, conorbranagan commented on docker/docker_linux.go
> +				err = json.Unmarshal(bytes, &jsonMap)
Doing a marshal then unmarshal like this is going to be pretty inefficient at higher container volumes (json is pretty slow in go). With an explicit struct you can avoid this altogether

2016-12-30 15:39 UTC, conorbranagan commented on docker/docker_linux.go
> +func GetContainerStats() (map[string]ContainerStat, error) {
`GetContainerStatByPID`?

2016-12-30 15:39 UTC, conorbranagan commented on docker/docker_linux.go
> +					containerMap[pid] = constainerStat
this creates a copy of the container stat for every pid in that container. if # pids / container is low than this won't matter

2016-12-30 15:39 UTC, conorbranagan commented on internal/common/common.go
> +func ReadDirectory(path string) ([]string, error) {
nit: ListDirectory seems clearer (to me) what this will return. ReadDirectory seems like you might be the contents of all files in the directory

2017-01-03 22:19 UTC, z0br0wn commented on docker/docker_linux.go
> +					containerMap[pid] = constainerStat
ideally there should be only 1 pid / container (https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/run-only-one-process-per-container), i doubt this is strictly followed but i think the count should stay pretty low.

2017-01-04 16:21 UTC, conorbranagan approved these changes

2017-01-04 17:51 UTC, merged